# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-latest'


steps:

- task: CmdLine@2
  inputs:
    script: |
      cp -r . $(Build.SourcesDirectory)
      sleep 5

- task: Gradle@2
  inputs:    
    gradleWrapperFile: android/gradlew
    workingDirectory: $(Build.SourcesDirectory)
    options: '--debug'
    tasks: 'build'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/android'
    ArtifactName: 'drop'
    publishLocation: 'Container'